### ISSUE TITLE
404 error with KubeVirt virtualization

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#44]
When adding the OpenShift provider, and selecting the KubeVirt virtualization, if the openshift doesn't have kubevirt but the token for Virtualization validation is successful, we get the error
`Credential validation was not successful: HTTP status code 404, 404 Not Found`

**Comment by vatsalparekh** [comment]
@masayag

**Comment by masayag** [comment]
The reason for the 404 is due to the use of `kubevirt_client` in order to access the `versions`.
Since kubevirt isn't deployed on the server, the action fails.

The fix should replace `kubevirt_client` with `core_client` in:
`api_versions = kubevirt_client.api["versions"]`

https://github.com/ManageIQ/manageiq-providers-kubevirt/blob/master/app/models/manageiq/providers/kubevirt/infra_manager/connection.rb#L94
