### ISSUE TITLE
virtualization gets affected with Default token change

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#70]
For a existing provider, which had both default and virtualization tokens same, and then that token is deleted from openshift, if we change token for just default with the new created token (which also is valid token for virtualization), the virtualization seems to be working fine where it should not be.

**Comment by pkliczewski** [comment]
@cben How it works in kubernetes or openshift provider?

**Comment by cben** [comment]
Let me make sure I get the scenario right:

1. create provider with two endpoints with same valid token
  (for kubevirt, this also creates 2nd manager with `endpoint_created` hook)
2. invalidate old token & generate new one in openshift
3. update only `default` endpoint in manageiq with new token.
  actually what you update is the `bearer` Authentication record (corresponding to `default` endpoint)?
4. Expected: kubevirt manager no longer works because it's configured with old invalid token?
   Actual: kubevirt manager works?

I don't remember if I ever tested changing tokens.

Looking at code, kubevirt connects using `kubevirt` Authentication and `default` Endpoint:
https://github.com/ManageIQ/manageiq-providers-kubevirt/blob/b140661b7adddfd1ab690a528eefd3a5c4fea327/app/models/manageiq/providers/kubevirt/infra_manager.rb#L117-L122
Hmm, but that's the child manager.
Can you remind me, IIRC child managers don't have their own endpoints / auth, they just reference the parents?  But I can't find it now in the code...

**Comment by masayag** [comment]
@cben 
> Can you remind me, IIRC child managers don't have their own endpoints / auth, they just reference the parents? But I can't find it now in the code...

Did you refer to this:

https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/virtualization_manager_mixin.rb#L13

**Comment by vatsalparekh** [comment]
So this seems to be working fine now on latest master today

One enhancement I would suggest is to show the error somewhere, the auth status on the provider icon has `!`, there should be more details about it
![screenshot from 2018-05-30 17-12-33](https://user-images.githubusercontent.com/6758282/40718243-fc314d32-642c-11e8-8843-f9464e4d8686.png)

**Comment by pkliczewski** [comment]
@vatsalparekh What we can do is check whether we are consistent with other providers. If there is anything to improve we will do it.
